# @package _global_

alg: mend_augdoc
lr: 1e-6
train_base: False
transform_lr: 1e-6
edit_lr: 1e-4
lr_lr: 1e-4
mend:
  one_sided: False
  n_hidden: 1
  hidden_dim: null
  init: id
  norm: True
  combine: True
  x_only: False
  delta_only: False
  act: relu
  rank: 1920
  mlp_class: IDMLP
  shared: True
  doc_loss_coeff: 1.
  aug_loss_coeff: 1.
  aug_loss_type: "nll" # nll, ict_distill
  ict_contra_coeff: 0.
