model_name: EleutherAI/gpt-neo-2.7B
editor:
  type: FineTuning
  trainable_pattern: '.'
  opt_name: AdamW
  opt_kwargs:
    lr: 4e-6
    weight_decay: 0.0
  minibatch_tokens: 1024
  steps: 10
  early_stop: 0.1
  train_mode: False
  ict_distill: True
  edit_loss_coeff: 0.8
  aug_loss_coeff: 0.2
  kl_coeff: 0.5
  ict_contra_coeff: 0.6
  