model_name: gpt2-xl
preprocess: stanford_openie
simplification: SimplificationWrapper
editor:
  type: MENDWrapper
  model_dir: baselines/mend/weights
  hparams: {
    "lr_scale": 1.0,
    "n_toks": 10,
    "model_name": "gpt2-xl",
    "counterfact": false,
    "zsre": false,
    "mini": false
  }